### ISSUE TITLE
Use Docker Compose from portainer and got this error

### ISSUE THREAD

**Issue by jiatao99** [koalazak/rest980#58]
I use the Portainer example you provided and swap to my BLID, PASSWORD etc. The only difference is I swapped "3000:3000" to "3060:3060" because port 3000 an8080 has already been used. When I try to start the docker image, I got the npm error. Please see log below

```
# Docker Portainer Stack
###################################
version: "2"
services:
  rest980:
    container_name: rest980
    image: koalazak/rest980:latest
    ports:
      - "3060:3060"
    environment:
      - BLID=<BLID>
      - PASSWORD=<PW>
      - ROBOT_IP=<IP>
      - FIRMWARE_VERSION=2
    restart: unless-stopped
  php-nginx:
    container_name: php-nginx
    image: webhippie/php-nginx:latest
    environment:
      NGINX_WEBROOT: "/app"
    volumes:
      - /mnt/data/supervisor/homeassistant/vacuum:/app
    ports:
      - "3001:6666"
    restart: unless-stopped
```

```
    at new cloud (/usr/src/app/node_modules/dorita980/index.js:12:10)


    at /usr/src/app/routes/api.js:33:46


    at handleIP (/usr/src/app/routes/api.js:26:68)


    at Object.<anonymous> (/usr/src/app/routes/api.js:27:1)


    at Module._compile (module.js:577:32)


    at Object.Module._extensions..js (module.js:586:10)


    at Module.load (module.js:494:32)


    at tryModuleLoad (module.js:453:12)


    at Function.Module._load (module.js:445:3)


    at Module.require (module.js:504:17)


    at require (internal/module.js:20:19)


    at Object.<anonymous> (/usr/src/app/app.js:11:16)


    at Module._compile (module.js:577:32)


    at Object.Module._extensions..js (module.js:586:10)


    at Module.load (module.js:494:32)


    at tryModuleLoad (module.js:453:12)


    at Function.Module._load (module.js:445:3)


    at Module.require (module.js:504:17)


    at require (internal/module.js:20:19)


    at Object.<anonymous> (/usr/src/app/bin/www:7:11)


    at Module._compile (module.js:577:32)




npm ERR! Linux 5.7.0-0.bpo.2-amd64


npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"


npm ERR! node v6.17.1


npm ERR! npm  v3.10.10


npm ERR! code ELIFECYCLE


npm ERR! rest980@2.1.0 start: `node ./bin/www`


npm ERR! Exit status 1




 


npm ERR! Failed at the rest980@2.1.0 start script 'node ./bin/www'.


npm ERR! Make sure you have the latest version of node.js and npm installed.


npm ERR! If you do, this is most likely a problem with the rest980 package,


npm ERR! not with npm itself.


npm ERR! Tell the author that this fails on your system:


npm ERR!     node ./bin/www


npm ERR! You can get information on how to open an issue for this project with:


npm ERR!     npm bugs rest980


npm ERR! Or if that isn't available, you can get their info via:


npm ERR!     npm owner ls rest980


npm ERR! There is likely additional logging output above.




npm ERR! Please include the following file with any support request:


npm ERR!     /usr/src/app/npm-debug.log




> rest980@2.1.0 start /usr/src/app


> node ./bin/www




WARNING: NODE_ENV value of 'production' did not match any deployment config file names.


WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode


/usr/src/app/node_modules/dorita980/lib/v2/cloud.js:7


  throw new Error('Not implemented.');


  ^




Error: Not implemented.


    at dorita980 (/usr/src/app/node_modules/dorita980/lib/v2/cloud.js:7:9)


    at new cloud (/usr/src/app/node_modules/dorita980/index.js:12:10)


    at /usr/src/app/routes/api.js:33:46


    at handleIP (/usr/src/app/routes/api.js:26:68)


    at Object.<anonymous> (/usr/src/app/routes/api.js:27:1)


    at Module._compile (module.js:577:32)


    at Object.Module._extensions..js (module.js:586:10)


    at Module.load (module.js:494:32)


    at tryModuleLoad (module.js:453:12)


    at Function.Module._load (module.js:445:3)


    at Module.require (module.js:504:17)


    at require (internal/module.js:20:19)


    at Object.<anonymous> (/usr/src/app/app.js:11:16)


    at Module._compile (module.js:577:32)


    at Object.Module._extensions..js (module.js:586:10)


    at Module.load (module.js:494:32)


    at tryModuleLoad (module.js:453:12)


    at Function.Module._load (module.js:445:3)


    at Module.require (module.js:504:17)


    at require (internal/module.js:20:19)


    at Object.<anonymous> (/usr/src/app/bin/www:7:11)


    at Module._compile (module.js:577:32)




npm ERR! Linux 5.7.0-0.bpo.2-amd64


npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"


npm ERR! node v6.17.1


npm ERR! npm  v3.10.10


npm ERR! code ELIFECYCLE


npm ERR! rest980@2.1.0 start: `node ./bin/www`


npm ERR! Exit status 1




 


npm ERR! Failed at the rest980@2.1.0 start script 'node ./bin/www'.


npm ERR! Make sure you have the latest version of node.js and npm installed.


npm ERR! If you do, this is most likely a problem with the rest980 package,


npm ERR! not with npm itself.


npm ERR! Tell the author that this fails on your system:


npm ERR!     node ./bin/www


npm ERR! You can get information on how to open an issue for this project with:


npm ERR!     npm bugs rest980


npm ERR! Or if that isn't available, you can get their info via:


npm ERR!     npm owner ls rest980


npm ERR! There is likely additional logging output above.




npm ERR! Please include the following file with any support request:


npm ERR!     /usr/src/app/npm-debug.log
```
